/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 death_star_trench_run.glb --transform
Author: Daniel (https://sketchfab.com/DanielAndersson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/death-star-trench-run-9f2a107b73e44941b4978444ff65593a
Title: Death Star Trench Run
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";

export function Trench(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/death_star_trench_run-transformed.glb"
  );

  useEffect(() => {
    materials.Hullplates2.metalness = 0.3;
    materials.Hullplates2.roughness = 0.5;
    materials.Hullplates2.color = new THREE.Color(0x8e8e8e);
  }, []);

  useFrame(({ camera }) => {
    if(camera.position.z - group.current.position.z > 132.5) {
      group.current.position.z = camera.position.z;
    }
  });
  return (
    <group ref={group} {...props} rotation-y={Math.PI} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
      {Array(10).fill().map((_, i) => (
        <group key={i} position={[i * 26.5, 0, 0]} scale={1}>
          <mesh
            geometry={nodes.DeathStarTrench_1.geometry}
            material={materials.Hullplates2}

          />
          <mesh
            geometry={nodes.DeathStarTrench_2.geometry}
            material={materials.Hullplates2}

          />
        </group>
      ))}
        
       </group>
    </group>
  );
}

useGLTF.preload("/death_star_trench_run-transformed.glb");
