/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tie.glb --transform
Author: metalmorag (https://sketchfab.com/metalmorag)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tie-5bcaa60ed5ce4a51b4233aed418f2280
Title: TIE
*/

import React, { useRef } from 'react'
import { useGLTF, PositionalAudio } from '@react-three/drei'

export function Tie(props) {
  const { nodes, materials } = useGLTF('/tie-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow position-y={-7} geometry={nodes.Object_2.geometry} material={materials.surfaceShader1SG} rotation={[-Math.PI / 2, 0, 0]} />
      <PositionalAudio
          url="/sounds/tieEngine.wav"
          distance={5}
          loop={true}
          autoplay={true}

        />
    </group>
  )
}

useGLTF.preload('/tie-transformed.glb')
